[package]
name = "js-py-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.5"
tokio = {version = "1.39.2",features = ['full']}
tokio-tungstenite = "0.23.1"
url = "2.5.2"
futures-util = "0.3.30"
crossterm = "0.28.1"